### ISSUE TITLE
Replace text and label properties with slots

### ISSUE THREAD

**Issue by silentHoo** [inovex/elements#403]
### Refactor Request

- [x] ino-form-row: `label` -> default slot?
   - default slot is currently in use, no changes useful
- [x] ino-chip: `label` -> default slot? (#559)
- [x] ino-header: `text` -> default slot? (#543)
- [x] ino-list-item: `text` -> default slot?
   - default slot is currently in use for user content like images
   - named slot `primary` exists
- [x] ino-list-item: `secondary-text` -> named slot?
   - named slot `secondary` exists
- [ ] ino-fab: `label` -> default slot?
- [x] ino-nav-item
   - `text` -> default slot?
   - `secondary-text` -> named slot?
     - Component will be replace by `ino-list-item` in future
- [x] ino-control-item 
  - `text` -> default slot? 
  -  `secondary-text` -> named slot?)
     - depends on `ino-list-item` 
     - is slot delegating possible?
     - can possible replaced by composition example?
- [x] ino-tab: `label` -> default slot? (#544)
- [x] ino-tooltip: `label` -> default slot? (#558)
- [x] ino-snackbar: `message` -> default slot? (#542)
- [x] ino-label: `label` -> default slot?
  - is only a internal component
  - used by `ino-input`, `ino-textarea`, `ino-select`

Please consider valuable choices for each component.

*Acceptance Criteria*:
- Add a deprecation warning
- Allow both solutions: label/text/message and slot
- Add a new issue removing the label/text/message behaviour

**Comment by BenPag** [comment]
Component remvoal ideas:

* ino-form-row
* ino-nav-item (can be replaced by ino-list-item)
