### ISSUE TITLE
Implement new color scheme

### ISSUE THREAD

**Issue by MBuchberger** [inovex/elements#859]
**Description**
The new colors scheme exists of two palettes: Primary and Neutral - both are named from 1 - 12 - and four alert colors: informational, success, error and warning + related light versions. 

P-06 is the actual primary color - the others are gradations of that color.

**Where to implement?**
- Show the new colors in the Styleguide (Inspiration: https://carbondesignsystem.com/guidelines/color/overview/)
- Change the Color in the Code of the following Components 

Input
- [x] **ino-autocomplete**: #3d40f5, Base -> P-05
- [x] **ino-currency-input**:  #3d40f5, Base -> P-05
- [x] **ino-datepicker**: #3d40f5, Base -> P-05; flatpickr-calendar #3d40f5, Base -> P-05
- [x] **ino-input**:  #3d40f5, Base -> P-05
- [x] **ino-markdown-editor**: _change in colab with a designer_
- [x] **ino-option-group**:  #3d40f5, Base -> P-05
- [x] **ino-option**: #3d40f5, Base -> P-05
- [x] **ino-range**: #3d40f5, Base -> P-05
- [x] **ino-select**: #3d40f5, Base -> P-05 - hover / select state: _change in colab with a designer_
- [x] **ino-textarea**: #3d40f5, Base -> P-05

Button
- [x] **ino-chip**: check in colab with a designer
- [x] **ino-fab-set**: #3d40f5, Base -> P-06
- [x] **ino-icon-button**: #3d40f5, Base -> P-06
- [x] **ino-segment-button**: _check in colab with a designer_
- [x] **ino-segment-group**: _check in colab with a designer_

Structure
- [x] **ino-control-item**: _check in colab with a designer_
- [x] **ino-list-divider**: _change in colab with a designer_
- [x] **ino-list-item**: _change in colab with a designer_
- [x] **ino-list**: _change in colab with a designer_
- [x] **ino-menu**: _change in colab with a designer_
- [x] **ino-nav-drawer**: _change in colab with a designer_
- [x] **ino-nav-item**: _change in colab with a designer_
- [x] **ino-tab-bar**: _change in colab with a designer_
- [x] **ino-tab**: _change in colab with a designer_
- [x] **ino-table-header-cell**: #3d40f5, Base -> P-05; Grey: _change in colab with a designer_
- [x] **ino-table**: #3d40f5, Base -> P-05; Grey: _change in colab with a designer_

Notification
- [x] **ino-progress-bar**: #3d40f5, Base -> P-05
- [x] **ino-nackbar**: Alert Colors 
- [x] **ino-spinner**: #3d40f5, Base -> P-05
- [x] **ino-tooltip**: #3d40f5, Base -> P-05

What means change / check in colab with a designer?
We will check which color fits best directly in code

Where you find the color scheme?
See elements slack channel bookmarks
